# Generated by Django 4.1.5 on 2023-04-22 17:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0004_profile_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
