# Generated by Django 4.1.5 on 2023-04-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0008_rename_updates_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-created_at']},
        ),
    ]
