# Generated by Django 4.1.5 on 2023-04-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0009_alter_update_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={},
        ),
    ]
